# -*- coding: utf-8 -*-
"""alarmbyAyoolorunnimi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1BK2NTAGKxzJ3WQ7KD5GPenypFCldk9

## ⏰ Desktop Alarm Utility (v1.0.3)
A precision time-management tool designed for desktop and cloud-terminal environments.
### ⏰ Desktop Alarm Utility (v1.0.3 - STABLE)
* **Status:** ✅ Verified & Functional
* **Key Fix:** Standardized meridiem parsing using `%I:%M %p`. This resolved the 'silent failure' bug where mismatched string delimiters prevented alarm triggers.
* **User Interface:** Added real-time confirmation messages (e.g., "Alarm successfully set for...") to provide immediate user feedback.

### 🌟 Features
* **Dual-Clock Support:** Seamlessly handles both 12-hour (AM/PM) and 24-hour input formats using `%I:%M:%p` normalization.
* **Timezone Resilience:** Hard-coded to `America/Toronto` via `zoneinfo` to ensure alert accuracy regardless of system drift or VPN location.
* **Resource Efficiency:** Implements a 1-second polling interval to maintain sub-second accuracy without taxing CPU cycles.
* **Defensive Error Handling:** Includes `try-except` blocks for timezone validation and input sanitation.

### ⌨️ Usage Example
When prompted, enter time as:
* `8:30` (Automatically treated as AM/PM depending on system state)
* `20:30` (Military time support)
"""

from datetime import datetime
from zoneinfo import ZoneInfo
import random
import time

def checker(target_alarm_time):
    # target_alarm_time is now a clean string like "12:05 AM"
    print(f"✅ Alarm successfully set for: {target_alarm_time}")
    while True:
        try:
            # We must format the current time EXACTLY like the target string
            now_toronto = datetime.now(ZoneInfo("America/Toronto"))
            current_time_str = now_toronto.strftime('%I:%M %p') # Note the space before %p

            if current_time_str == target_alarm_time:
                print("\n🔔 ALARM! Time to wake up!")
                print("\a" * 5)
                break
        except Exception as e:
            print(f"Error in background check: {e}")
            break
        time.sleep(1)

def Clock():
    j = random.randint(1, 9999)
    print(f"Welcome, Guest {j}!")

    while True:
        user_input = input("\nEnter time (e.g. 12:05 AM or 8:30 PM) or 'exit': ").strip().upper()

        if user_input in ['BREAK', 'EXIT', 'QUIT']:
            print(f"Goodbye, {j}!")
            break

        try:
            # We parse the user input. Using '%I:%M %p' (with a space) is more standard.
            # This turns "12:05 AM" into a formal time object
            standard_time = datetime.strptime(user_input, '%I:%M %p')

            # We convert that object back into a string for the checker
            final_alarm_string = standard_time.strftime('%I:%M %p')

            checker(final_alarm_string)
            break
        except ValueError:
            print("❌ Format Error! Please use HH:MM AM/PM (Example: 12:05 AM)")

Clock()

import zoneinfo # Import the entire zoneinfo module

# Get all available timezones
available_zones = zoneinfo.available_timezones()

# Print them out
print("Available IANA Timezones:")
for tz in sorted(available_zones):
    print(tz)