# -*- coding: utf-8 -*-
"""Drake equation class  v 1.0.2 project by Ayoolorunnimi

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNMxkYyj8Y1m3GlofIpVC6z72d9-vtC7

# 🌌 Maximilian's Universe Manager v1.0.2

![Python](https://img.shields.io/badge/python-3.10+-blue.svg)
![License](https://img.shields.io/badge/license-Apache%202.0-orange.svg)
![GUI](https://img.shields.io/badge/UI-ipywidgets-purple)
![Verified](https://img.shields.io/badge/Logic-AI--Verified-green)

An advanced Object-Oriented simulation tool for calculating the probability of extraterrestrial civilizations using the Drake Equation. This project combines astronomical research with reactive dashboard engineering.
### ⚠️ Note on Notebook Rendering
GitHub may occasionally display an 'Invalid Notebook' error due to the interactive `ipywidgets` state.
**To view the full interactive Universe Manager:**
1. Click the 'Open in Colab' badge at the top of the notebook.
2. Run all cells to initialize the GUI.

---

## 🚀 Key Features

* **Reactive Dashboard:** Full GUI implementation using `ipywidgets` for real-time parameter tuning without code modification.
* **Object-Oriented Architecture:** Built on a robust Class-based structure for stateful simulation and modularity.
* **Persistent Data Logging:** Automatic JSON serialization to `log.json` for historical audit trails and session recovery.
* **AI-Council Verified:** Logic and math cross-validated via a multi-model ensemble (ChatGPT, Gemini, Perplexity, and Google AI) for maximum accuracy.
* **ISO Timestamping:** Precise record-keeping using `ZoneInfo` for time-zone aware simulation logs.

---

## 🛠️ Technical Logic

While the core math is intentionally streamlined for transparency, the simulator provides deep insights through:
1.  **Direct Drake Output ($N$):** The standard linear probability chain.
2.  **Binomial Extrapolation:** Calculating the probability of success across a specific sample size (e.g., 100 stars) using:
    $$P_{success} = 1 - (1 - p)^n$$

---

## 📦 Installation & Setup

Since this project is optimized for **Google Colab (transient VM)**, simply open the notebook and run the cells. For local execution in a `venv`:


```bash
pip install -r requirements.txt
python main.py
"""

from datetime import datetime
import time
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError
import json
from json.decoder import JSONDecodeError
import ipywidgets as widgets
from IPython.display import display, clear_output
class DrakeEquation:
  def __init__(self, NOG, R, fp, ne, fl, fi, fc, L, TSIG):
    self.R = R
    self.fp = fp
    self.ne = ne
    self.fl =fl
    self.fi = fi
    self.fc = fc
    self.L = L
    self.TSIG = TSIG
    self.NOG = NOG
    self.First = None
    self.time_now_log = datetime.now(ZoneInfo("America/Toronto"))

  def Calculation(self):
    try:
      print("booting up...")
      dt = time.perf_counter()
      time.sleep(5)
      self.First = self.R * self.fp * self.ne * self.fl * self.fi * self.fc * self.L
      print(f"There would be {self.First:.0f} civilizations in {self.NOG}")
      self.prob_1 = self.First/self.TSIG
      print(f'The probability of {self.NOG} having civilizations would be {self.prob_1:.6f}')
      self.prob_2 = 1-(1-self.prob_1)**100
      print(f'The probability of a 100 stars in {self.NOG} having civilizations would be {self.prob_2:.2%}')
      et = time.perf_counter()
      end = et-dt
      print(f'Thought for {end:.0f} seconds')
    except OverflowError:
      print('What have you done!!!!! NOOOOOO!!!!!!!! Anyways you inputted values too high')
      print('We would make sure version 1.0.3 stops you from doing that')

  def load(self, body_name):
    try:
        with open("log.json", "r") as file:
            data = json.load(file)

            if body_name in data:
                history = data[body_name]

                self.R = history.get("Rate_star_form", self.R)
                self.fp = history.get("Star/plan", self.fp)
                self.ne = history.get("hab_plan/star_sys", self.ne)
                self.fl = history.get("frac_hab_planlife_dev", self.fl)
                self.fi = history.get("frac_plan_intel_life_form", self.fi)
                self.fc = history.get("frac_civi_dev_detect_tech", self.fc)
                self.L = history.get("ave_lifespan_comms_civi", self.L)

                print(f"Successfully loaded history for {body_name}")
            else:
                print(f"No entry found for {body_name} in the logs.")

    except (FileNotFoundError, json.JSONDecodeError):
        print("Log not created or is empty/corrupt.")

  def save(self):
      try:
        with open("log.json", "r") as file:
          data = json.load(file)
      except (FileNotFoundError, json.JSONDecodeError):
        data = {}
      save_time = datetime.now(ZoneInfo("America/Toronto"))
      data[self.NOG] = {
          "Rate_star_form": self.R,
          "Star/plan": self.fp,
          "hab_plan/star_sys": self.ne,
          "frac_hab_planlife_dev": self.fl,
          "frac_plan_intel_life_form": self.fi,
          "frac_civi_dev_detect_tech": self.fc,
          "ave_lifespan_comms_civi": self.L,
          "time_of_rec": str(self.time_now_log),
          "save_time" : str(save_time)
          }
      with open("log.json", "w") as file:
        json.dump(data, file, indent=4)
        print(f"data saved for {self.NOG}")

def UI():
    # 1. Styling the Dashboard
    style = {'description_width': 'initial'}
    layout = widgets.Layout(width='450px')

    # 2. Creating the UI Sliders
    galaxy_name = widgets.Text(value='Milkyway_galaxy', description='Galaxy Name:', style=style)
    r_slider = widgets.FloatSlider(value=3.0, min=0.1, max=20.0, step=0.1, description='Star Formation Rate (R):', style=style, layout=layout)
    fp_slider = widgets.FloatSlider(value=0.5, min=0.01, max=100, step=0.01, description='Fraction with Planets (fp):', style=style, layout=layout)
    ne_slider = widgets.FloatSlider(value=2.0, min=0.1, max=100, step=0.1, description='Habitable Planets (ne):', style=style, layout=layout)
    fl_slider = widgets.FloatSlider(value=1.0, min=0.01, max= 100, step=0.01, description='Fraction Developing Life (fl):', style=style, layout=layout)
    fi_slider = widgets.FloatSlider(value=0.1, min=0.01, max=100, step=0.01, description='Fraction Intelligent Life (fi):', style=style, layout=layout)
    fc_slider = widgets.FloatSlider(value=0.1, min=0.01, max=100, step=0.01, description='Fraction Tech/Detect (fc):', style=style, layout=layout)
    l_slider = widgets.IntSlider(value=10000, min=1000, max=10000000, step=10000, description='Civ Lifespan (L):', style=style, layout=layout)

    # 3. Action Button and Output Area
    calc_button = widgets.Button(description="Run Simulation", button_style='success', icon='rocket')
    output = widgets.Output()

    def on_button_clicked(b):
        with output:
            clear_output()
            # Instantiate the class using current slider values
            app = DrakeEquation(
                galaxy_name.value,
                r_slider.value,
                fp_slider.value,
                ne_slider.value,
                fl_slider.value,
                fi_slider.value,
                fc_slider.value,
                l_slider.value,
                TSIG=10**11 # Constant for total stars
            )
            print(f"--- 🌌 MAXIMILIAN'S UNIVERSE MANAGER V1.0.2 ---")
            app.Calculation()
            app.save()

    calc_button.on_click(on_button_clicked)

    # 4. Display everything
    display(galaxy_name, r_slider, fp_slider, ne_slider, fl_slider, fi_slider, fc_slider, l_slider, calc_button, output)

# Launch immediately
UI()